# Generated by Django 5.0.4 on 2024-09-11 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_video_weblog_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
