# Generated by Django 5.0.4 on 2024-09-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('timeframe', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=100)),
            ],
        ),
    ]
